### ISSUE TITLE
"python setup.py test" failed

### ISSUE THREAD

**Issue by ghost** [pisilinux/piksemel#1]
When I run setup.py with "test" argument, I get an error:
```
Traceback (most recent call last):
  File "tests/traverse.py", line 29, in <module>
    node = next(node)
TypeError: 'piksemel.Node' object is not an iterator
traverse.py failed!
```

**EDIT:** `python --version` output is `Python 3.7.3`.

**Comment by eersoy93** [comment]
Yeni depomda bunu düzelttim. Bu konuyu açan da bendim, bu benim yeni hesabım bu arada. Düzeltme işlemesi:

https://github.com/Ersoy-Kardesler-Pisi-Repositories/piksemel/commit/d01d72e99113918a854a07ce7d0ad4a2860890f0

Bu arada düzelttikten sonra tüm testler çalışıyor.

**Comment by eersoy93** [comment]
For the pull request of this issue, see #3 .

**Comment by safaariman** [comment]
Should be fixed now. If the problem still exists feel free to open another issue.

Have a good day :)
